FROM node:19 AS builder

WORKDIR /app

COPY package.json /app
COPY yarn.lock /app

RUN yarn install

COPY . /app

RUN yarn build

FROM node:19-alpine

WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/docker.env ./.env
COPY --from=builder /app/docker/docker_scripts/start.sh ./start.sh

RUN chmod +x ./start.sh

ENTRYPOINT ["./start.sh"]
