version: '3.8'
services:
  http-server:
    build:
      context: ../http-server
      dockerfile: ../docker/buildHttp.Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    volumes:
      - ../http-server:/app

  websocket-server:
    build:
      context: ../websocket-server
      dockerfile: ../docker/buildWebsocket.Dockerfile
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    volumes:
      - ../websocket-server:/app

  db:
    image: postgres
    environment:
      - POSTGRES_USER=badak
      - POSTGRES_PASSWORD=Blindtest123!
      - POSTGRES_DB=blindtestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
