services:
  app:
    image: blind
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - NODE_SERVER_PORT=3002
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=badak
      - POSTGRES_DB=blindtestdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
